# Generated by Django 5.2.8 on 2025-12-01 07:37

import apps.registry.partners.validators.field_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ОРФ"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            apps.registry.partners.validators.field_validators.validate_inn
                        ],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            apps.registry.partners.validators.field_validators.validate_ogrn
                        ],
                        verbose_name="ОГРН",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        validators=[
                            apps.registry.partners.validators.field_validators.validate_kpp
                        ],
                        verbose_name="КПП",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                ("validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_partners",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнёр",
                "verbose_name_plural": "Партнёры",
                "ordering": ["name"],
            },
        ),
    ]
