# Generated by Django 5.2.8 on 2025-12-02 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Проверено"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время проверки"
            ),
        ),
        migrations.CreateModel(
            name="PartnerMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Внутренний идентификатор сотрудника в партнерской организации",
                        max_length=100,
                        null=True,
                        verbose_name="Табельный номер",
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True,
                        help_text="Корпоративная почта сотрудника",
                        max_length=254,
                        null=True,
                        verbose_name="Рабочий email",
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True,
                        help_text="Корпоративный телефон",
                        max_length=100,
                        null=True,
                        verbose_name="Рабочий телефон",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("employee", "Сотрудник"),
                            ("manager", "Менеджер"),
                            ("director", "Директор"),
                            ("accountant", "Бухгалтер"),
                            ("admin", "Администратор партнера"),
                        ],
                        default="employee",
                        help_text="Определяет уровень доступа и права в системе",
                        max_length=50,
                        verbose_name="Роль в партнерской организации",
                    ),
                ),
                (
                    "can_manage_members",
                    models.BooleanField(
                        default=False,
                        help_text="Может добавлять/удалять других сотрудников партнера",
                        verbose_name="Может управлять членами партнера",
                    ),
                ),
                (
                    "can_view_finance",
                    models.BooleanField(
                        default=False,
                        help_text="Доступ к финансовой информации партнера",
                        verbose_name="Может просматривать финансы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Сотрудник активен в организации",
                        verbose_name="Активный сотрудник",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Партнерская организация, к которой относится сотрудник",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="partners.partner",
                        verbose_name="Партнер",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привязка к пользователю системы (если есть аккаунт)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь системы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Член партнера",
                "verbose_name_plural": "Члены партнеров",
                "ordering": ["partner", "name"],
                "indexes": [
                    models.Index(
                        fields=["partner", "employee_id"],
                        name="partners_pa_partner_6209c2_idx",
                    ),
                    models.Index(
                        fields=["partner", "user"],
                        name="partners_pa_partner_91c88f_idx",
                    ),
                    models.Index(
                        fields=["partner", "is_active"],
                        name="partners_pa_partner_7927b4_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="partners_pa_user_id_148918_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("employee_id__isnull", False)),
                        fields=("partner", "employee_id"),
                        name="unique_employee_per_partner",
                    )
                ],
            },
        ),
    ]
