# Generated by Django 5.2.8 on 2025-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_add_partner_member_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="partnermember",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Название",
            ),
        ),
    ]
