# Generated by Django 5.2.8 on 2025-12-07 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_alter_partnermember_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                (
                    "inn",
                    models.CharField(max_length=12, unique=True, verbose_name="ИНН"),
                ),
                (
                    "ogrn",
                    models.CharField(max_length=15, unique=True, verbose_name="ОГРН"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Контактный email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=100, verbose_name="Контактный телефон"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает рассмотрения"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка партнера",
                "verbose_name_plural": "Заявки партнеров",
                "ordering": ["-created_at"],
            },
        ),
    ]
