# Generated by Django 5.2.8 on 2025-12-07 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partnerapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerapplication",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата обработки"
            ),
        ),
        migrations.AddField(
            model_name="partnerapplication",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обработана администратором",
            ),
        ),
        migrations.AddField(
            model_name="partnerapplication",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Причина отклонения"
            ),
        ),
    ]
