# Generated by Django 5.2.8 on 2025-12-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_partnerapplication_processed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerapplication",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="partners.partner",
                verbose_name="Созданный партнёр",
            ),
        ),
    ]
