# Generated by Django 5.2.8 on 2025-12-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_partnerapplication_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Полный адрес пункта выдачи заказов",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "location_details",
                    models.CharField(
                        blank=True,
                        help_text="Детали расположения (например: цокольный этаж, 1-ый этаж)",
                        max_length=255,
                        null=True,
                        verbose_name="Расположение",
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        help_text="График работы ПВЗ (например: с 9:00 до 21:00)",
                        max_length=255,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Контактный телефон ПВЗ",
                        max_length=100,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Контактный email ПВЗ",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="ПВЗ активен для использования",
                        verbose_name="Активный",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Партнерская организация, которой принадлежит ПВЗ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_points",
                        to="partners.partner",
                        verbose_name="Партнер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт выдачи заказов",
                "verbose_name_plural": "Пункты выдачи заказов",
                "ordering": ["partner", "name"],
                "indexes": [
                    models.Index(
                        fields=["partner", "is_active"],
                        name="partners_pi_partner_991e19_idx",
                    ),
                    models.Index(
                        fields=["partner", "name"],
                        name="partners_pi_partner_87ce9d_idx",
                    ),
                ],
            },
        ),
    ]
