# Generated by Django 5.2.8 on 2025-12-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0007_pickuppoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partnermember",
            name="pickup_point",
            field=models.ForeignKey(
                blank=True,
                help_text="Привязка сотрудника к конкретному пункту выдачи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="partners.pickuppoint",
                verbose_name="Пункт выдачи",
            ),
        ),
        migrations.AddIndex(
            model_name="partnermember",
            index=models.Index(
                fields=["pickup_point"], name="partners_pa_pickup__5ca0b3_idx"
            ),
        ),
    ]
